### ISSUE TITLE
replace kernel failed for Clear Linxu OS

### ISSUE THREAD

**Issue by zyuan2x** [bryteise/ister#121]
I build one local kernel and want to replace the origin default one (kernel version: 4.14.7-497). 

**the content of my local kernel:**
├── config-4.15.0-rc4
├── lib
│   └── modules
│       └── 4.15.0-rc4
├── System.map-4.15.0-rc4
└── vmlinuz-4.15.0-rc4

**My work steps:**
1. copy vmlinuz-4.15.0-rc4 to /lib/kernel
2. delete the org.clearlinux.native.4.14.7-497 and rename vmlinuz-4.15.0-rc4 to  org.clearlinux.native.4.15.0-rc4
3. delete default-native
4. create new link "default-native" and link with new kernel org.clearlinux.native.4.15.0-rc4
5. delete origin kernel modules (4.14.7-497.native) in /lib/modules
6. copy new kernel modules 4.15.0-rc4 to /lib/modules and rename it with 4.15.0-rc4.native
7. reboot the machine
8. check the kernel version with command "uname -a"

I see the kernel version can't changes 
How to change the kernel version and load the new kernel and new kernel modules?

**Comment by bryteise** [comment]
You were quite close, sorry this is not documented at all (it is only inside the clr-boot-manager source).

First you'll want to add a cmdline-4.15.0-rc4 file (you can just copy one from the other kernels).

Next you will want to add namespaces to the kernels and their configs (so cmdline-4.15.0-rc4.custom for instance would be the file name for the cmdline, org.clearlinux.custom.4.15.0-rc4 would be the kernel filename, and the config would be config-4.15.0-rc4.custom) when you put them in /lib/kernel (you don't need the System.map).

The modules you placed correctly already. Next you should be able to run clr-boot-manager update and everything will be added to the EFI partition.

You also shouldn't manually remove the already existing files in /lib/{kernel,modules} because that is handled by clr-boot-manager though uninstalling a type entirely (native in this case) isn't supported yet. Currently clr-boot-manager just cleans up kernels that are no longer needed after an update (so the type has a newer version that booted is the basic policy).

**Comment by zyuan2x** [comment]
@bryteise  Very thanks for your details information about this issue. 
I have replace kernel successfully on Clear Linxu. Close this issue as it already resolve by customer.
