### ISSUE TITLE
Discussion of button theme

### ISSUE THREAD

**Issue by matthewrsj** [bryteise/ister#46]

**Comment by matthewrsj** [comment]
My personal preference is the dark cyan.

**Comment by bryteise** [comment]
So my preference order is yellow, dark cyan then light cyan. Green I actually like close to yellow but it is already close to the same color as the established color.

**Comment by ebrent8** [comment]
Colors: I like the cyan blues, then green, then yellow.  The cyan blues work also because they reinforce the Clear Linux brand colors on the website.

The connection established message in green/red is really good.  Grabs attention which is important since it's critical to continue.

Nice work.  This really enhances the UI.

**Comment by rnesius** [comment]
Yellow is my favorite, but I see "light cyan" does hit our logo so I could go with that.  

Small side note - can you make the "selection color map" have "light cyan on black" instead of "white on black"?  Should only have to change that in one or two places to make it the default everywhere? 

Let's go with Light Cyan for now...

**Comment by sofar** [comment]
in order of preference: light cyan, yellow, dark cyan.

**Comment by matthewrsj** [comment]
Closing, we are going with light cyan in #48 (for now)
